### ISSUE TITLE
Outputting sACN

### ISSUE THREAD

**Issue by faulder** [claudeheintz/LXDMXEthernet_library#3]
HI, 

I believe this library can be used to send sACN onto a network? Do you have any example code of  the library being used in an output situation?

Thanks

**Comment by claudeheintz** [comment]
Just added a DMX to Network example.  On my home network, I couldn't get either an old w5100 based ethernet shield or a newer w5500 ethernet shield 2 to send multicast packets.  They both unicast SACN without a problem, however.

**Comment by claudeheintz** [comment]
Apparently the ethernet shield sends out of network packets to the gateway.  (By definition, multicast addresses do not have a network component.)  My home network router does not forward multicast packets sent by the ethernet shield.  The workaround is to use broadcast instead of multicast and send sACN packets to the network's broadcast address, 192.168.1.255.

**Comment by faulder** [comment]
Thanks very much Claude! 

I've still got to do a bit more testing but the library is very intuitive and I've had no issues with broadcasting over a network. Thanks also for the investigation regarding multicast, that's much appreciated.
